CHANGES.txt
src/SplitContext.ts
src/SplitTreatments.tsx
src/types.ts
src/useClient.ts
src/useManager.ts
src/withSplitClient.tsx
src/withSplitFactory.tsx
src/withSplitTreatments.tsx
types/SplitContext.d.ts
types/types.d.ts
types/withSplitClient.d.ts
types/withSplitFactory.d.ts
types/withSplitTreatments.d.ts
webpack.common.js

- Updated build config to exclude React library from UMD bundle. 
- Updated the interface of SplitTreatments's child components.

Updated build config of UMD bundle

---

.travis.yml
CHANGES.txt
src/SplitClient.tsx
src/SplitContext.ts
src/__tests__/constants.test.ts
src/__tests__/testUtils/mockSplitSdk.ts
src/__tests__/testUtils/sdkConfigs.ts
src/constants.ts
src/useClient.ts
src/useManager.ts
src/useTrack.ts
src/useTreatments.ts
src/utils.ts
src/withSplitFactory.tsx
src/withSplitTreatments.tsx
types/constants.d.ts
types/withSplitFactory.d.ts
types/withSplitTreatments.d.ts

- Check and log specific errors due to missing features in no compatible React versions.

Check React version

---

CHANGES.txt
package-lock.json
package.json

Release version 1.2.0

---

CHANGES.txt
package-lock.json
package.json
types/constants.d.ts
types/useClient.d.ts
types/useManager.d.ts
types/useTrack.d.ts
types/useTreatments.d.ts

- Updated NPM dependencies to use last JS SDK version in favor of size reduction and vulnerability fixes. 
- Also Jest was updated to fix low severity vulnerabilities. TypeScript was updated to last version to suppress a `ts-jest` warning.

Updated NPM dependencies

---

.travis.yml
CHANGES.txt
package-lock.json
package.json

Update version and changelog for stable release
NA

Update version and changelog for stable release

---

.travis.yml
CHANGES.txt
package-lock.json
package.json

Prepare repo for stable release.

Release v1.2.4

---

CHANGES.txt
README.md
package-lock.json
package.json

Update Split SDK version to catch up with the latest changes.

Patch: Update Split package

---

CHANGES.txt
package-lock.json
package.json

Updating Splitio SDK Client's version

Release | v1.2.5

---

package-lock.json
package.json
types/splitio/splitio.d.ts

Fix minimist dependency vulnerability

---

.github/workflows/ci-cd.yml
.gitignore
package.json
version_replace.sh
webpack.common.js

CI-CD workflow update

---

LICENSE
README.md
src/utils.ts

Update README file

---

src/SplitTreatments.tsx
src/__tests__/SplitClient.test.tsx
src/__tests__/SplitTreatments.test.tsx
src/__tests__/testUtils/utils.tsx
src/__tests__/useClient.test.tsx
src/__tests__/withSplitClient.test.tsx
src/utils.ts

Update attributes binding logic

---

CHANGES.txt
package-lock.json
package.json
types/splitio/splitio.d.ts

Prepare release v1.8.0

---

CHANGES.txt
package-lock.json
package.json
types/splitio/splitio.d.ts

Release v1.8.0

---

.github/workflows/ci-cd.yml

Upload assets to us and eu (stage)

Upload assets to us and eu (stage)

---

.github/workflows/ci-cd.yml

Prevent failures when attempting to use a role that doesn't exist anymore.
Merge it.

Disable assets upload to Europe

---

.github/workflows/ci.yml
.github/workflows/update-license-year.yml
.gitignore
sonar-project.properties

Move the sonar config to its own file and reduce the amount of files to scan.

Simplify sonarqube workflow

---

src/SplitTreatments.tsx
src/__tests__/SplitTreatments.test.tsx
src/__tests__/constants.test.ts
src/__tests__/useTreatments.test.tsx
src/__tests__/withSplitTreatments.test.tsx
src/constants.ts

[SDKS-6942][DW] Update tests and constants

---

src/SplitTreatments.tsx
src/constants.ts
src/types.ts
src/useTreatments.ts
src/utils.ts
src/withSplitTreatments.tsx
types/SplitTreatments.d.ts
types/constants.d.ts
types/types.d.ts
types/useTreatments.d.ts
types/utils.d.ts
types/withSplitTreatments.d.ts

[SDKS-6947][DW] Update public methods splitName param

---

CHANGES.txt
README.md
src/__tests__/SplitTreatments.test.tsx
src/__tests__/testUtils/sdkConfigs.ts
src/types.ts
src/useTreatments.ts
src/withSplitTreatments.tsx
types/SplitTreatments.d.ts
types/types.d.ts
types/useTreatments.d.ts
types/withSplitTreatments.d.ts

[SDKS-6931][DW] Replace splits, splitName, webConsole and apikey

---

README.md

[SDKS-6964][DW] Replace BROWSER with CLIENT SIDE

---

README.md

[DW] UPDATE apiKey -> sdkKey

---

src/SplitFactory.tsx
src/__tests__/testUtils/mockSplitSdk.ts
src/utils.ts

Update how SDK version is overwritten

---

src/SplitClient.tsx
src/SplitFactory.tsx
src/useSplitClient.ts
src/utils.ts
types/utils.d.ts

- removed unused attributes param from getSplitSharedClient
- updated initAttributes signature

removed unused attributes param from getSplitSharedClient

---

.github/workflows/ci.yml
CHANGES.txt
package-lock.json
package.json
webpack.common.js
webpack.dev.js
webpack.prod.js

Prepare release v1.8.4

---

CHANGES.txt
package-lock.json
package.json
webpack.dev.js
webpack.prod.js

Prepare release v1.9.0

---

package-lock.json
src/__tests__/SplitTreatments.test.tsx
src/__tests__/useClient.test.tsx
src/__tests__/useSplitClient.test.tsx
src/__tests__/useSplitTreatments.test.tsx
src/__tests__/useTreatments.test.tsx
src/types.ts
src/useClient.ts
src/useSplitClient.ts
src/useSplitTreatments.ts
src/useTrack.ts
src/useTreatments.ts
src/utils.ts
types/types.d.ts
types/useClient.d.ts
types/useSplitClient.d.ts
types/useSplitTreatments.d.ts
types/useTrack.d.ts
types/useTreatments.d.ts

Options object for hooks arguments

---

CHANGES.txt
package-lock.json
package.json

Prepare release v1.12.1

---

CHANGES.txt
package-lock.json
package.json
src/SplitClient.tsx
src/__tests__/SplitClient.test.tsx
src/__tests__/SplitFactory.test.tsx
src/__tests__/SplitFactoryProvider.test.tsx
src/__tests__/SplitTreatments.test.tsx
src/__tests__/testUtils/mockSplitSdk.ts
src/types.ts
src/useSplitClient.ts
src/utils.ts
tsconfig.json

Release v1.13.0

---

.github/workflows/ci-cd.yml

Update actions for deprecation
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Check if the action workflow pass successfully

Bump artifact actions

---

.github/workflows/ci-cd.yml
CHANGES.txt
package-lock.json
package.json
src/__tests__/SplitTreatments.test.tsx
src/__tests__/useSplitTreatments.test.tsx
src/types.ts
src/useSplitTreatments.ts
src/utils.ts

Upgrade JS SDK and Add Impression Properties support

---

CHANGES.txt
package-lock.json
package.json
src/SplitFactoryProvider.tsx

Release v2.3.1
